#!/usr/bin/env bash

srcdir=`pwd`
dstdir=$HOME

files=(	'vim:.vim'
		'vim/vimrc:.vimrc'
		'git/gitconfig:.gitconfig'
		'git/gitignore:.gitignore'
		'sshconfig:.ssh/config'
		'bash/bashrc:.bashrc'
)

for filepair in ${files[@]} ; do
	src="$srcdir/${filepair%%:*}"
	dst="$dstdir/${filepair##*:}"

	mkdir -p ${dst%/*}

	if [ -L $dst ] ; then
		rm $dst
	fi

	if [ -f $dst ] || [ -d $dst ]; then
		echo "Warning! File '$dst' already exists and won't be overwritten!"
	else
		ln -s $src $dst
	fi
done

mkdir -p $srcdir/vim/tmp

git submodule init
git submodule update

# Fetch newest hub
rm $srcdir/bin/hub &> /dev/null
curl http://defunkt.io/hub/standalone -sLo $srcdir/bin/hub && chmod 755 $srcdir/bin/hub

# Fetch newest z
rm $srcdir/z.sh &> /dev/null
curl https://raw.github.com/rupa/z/HEAD/z.sh -sLo $srcdir/z.sh

# Fetch newest pathogen
rm $srcdir/vim/autoload/pathogen.vim &> /dev/null
mkdir -p $srcdir/vim/autoload $srcdir/vim/bundle
curl -so $srcdir/vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/HEAD/autoload/pathogen.vim
