#!/usr/bin/env bash

srcdir=`pwd`
dstdir=$HOME

files=(	'vim:.vim'
		'vim/vimrc:.vimrc'
		'git/gitconfig:.gitconfig'
		'git/gitignore:.gitignore'
		'bash/bashrc:.bashrc'
		'tmux:.tmux.conf'
)

install_filepair () {
	src="$srcdir/$1"
	dst="$dstdir/$2"
	echo "$1 -> $2"
	mkdir -p ${dst%/*}

	if [ -L $dst ] ; then
		rm $dst
	fi

	if [ -f $dst ] || [ -d $dst ]; then
		echo "Warning! File '$dst' already exists and won't be overwritten!"
	else
		ln -s $src $dst
	fi
}

for filepair in ${files[@]} ; do
	install_filepair "${filepair%%:*}" "${filepair##*:}"
done

# Fetch newest z
rm $srcdir/z.sh &> /dev/null
curl https://raw.github.com/rupa/z/HEAD/z.sh -sLo $srcdir/z.sh

# Optional tasks
for opt in "$@"; do
	case $opt in
		private)
			. $srcdir/private/deploy
			;;
	esac
done
