#!/usr/bin/env bash

srcdir=`pwd`
dstdir=$HOME

files=(	'vim:.vim'
		'vim/vimrc:.vimrc'
		'git/gitconfig:.gitconfig'
		'git/gitignore:.gitignore'
		'sshconfig:.ssh/config'
		'bash/bashrc:.bashrc'
)

for filepair in ${files[@]} ; do
	src="$srcdir/${filepair%%:*}"
	dst="$dstdir/${filepair##*:}"

	mkdir -p ${dst%/*}

	if [ -L $dst ] ; then
		rm $dst
	fi

	if [ -f $dst ] || [ -d $dst ]; then
		echo "Warning! File '$dst' already exists and won't be overwritten!"
	else
		ln -s $src $dst
	fi
done

# Fetch newest z
rm $srcdir/z.sh &> /dev/null
curl https://raw.github.com/rupa/z/HEAD/z.sh -sLo $srcdir/z.sh

# Fetch newest molokai
rm $srcdir/vim/colors/molokai.vim &> /dev/null
curl https://raw.github.com/tomasr/molokai/master/colors/molokai.vim -sLo $srcdir/vim/colors/molokai.vim

# Optional tasks
for opt in "$@"; do
	case $opt in
		vimbundle)
			git clone git://github.com/Shougo/neobundle.vim $srcdir/vim/bundle/neobundle.vim
			;;
	esac
done
