# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.luks.devices = [ { device = "/dev/disk/by-uuid/547f13b5-63f6-4d33-845f-3b7ae866c48d"; name = "crypt"; } ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.enableAllFirmware = true;

  swapDevices = [ ];

  nix.maxJobs = 4;

  fileSystems."/" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = "defaults,compress,subvolid=302";
  };
}
